# Mount Drive

In [97]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [98]:
# Project Directory path
project_dir = 'drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/'

In [99]:
import glob

# Using '*' pattern
print('\nNamed with wildcard *:')
for name in glob.glob(project_dir+'*'):
    print(name)

Named with wildcard *:
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn-Modelling.xlsx
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn-Modelling.csv
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn-Load.ipynb
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn-Modelling.gsheet
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn_Demo_Predict.ipynb
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn-Demo-EDA.ipynb

In [100]:
print(project_dir+'*')

drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/*

In [101]:
# Using '*' pattern
print('\nNamed with wildcard *:')
for name in glob.glob(project_dir+'*.csv'):
    print(name)

Named with wildcard *:
drive/MyDrive/UW.8740/Lab 02 - Feature Eng and Model Selection/CustomerChurn/Churn-Modelling.csv

In [102]:
import pandas as pd
pd.options.mode.chained_assignment = None

In [103]:
churn = pd.read_csv(project_dir+ 'Churn-Modelling.csv')
churn

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
0,1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0,NaN
2,3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1,NaN
3,4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0,NaN
4,5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9996,9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9997,9998,15584532,Liu,709,France,Female,36,7,0K,1,0,1,42085.58,1,NaN
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN
9999,10000,15628319,Walker,792,France,Female,28,4,130K,1,1,0,38190.78,0,NaN

# Verify unique values of columns

In [104]:
uniqueIDcount= churn['CustomerId'].nunique()
uniqueIDcount

10000

In [105]:
uniqueIDcount

10000

In [106]:
churn['CustomerId'].nunique()

10000

In [107]:
x = churn['CustomerId'].unique()
len(x)

10000

In [108]:
churn['CustomerId'].unique()

array([15634602, 15647311, 15619304, ..., 15584532, 15682355, 15628319])

In [109]:
len(churn['CustomerId'].unique())

10000

In [110]:
churn['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [111]:
churn['Geography'].nunique()

3

In [112]:
type(churn)

pandas.core.frame.DataFrame

In [113]:
len(churn['RowNumber'].unique())

10000

In [114]:
churn['RowNumber'].nunique()

10000

# Reset DataFrame index

In [115]:
churn.set_index('RowNumber', inplace=True)
churn

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1,NaN
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0,NaN
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1,NaN
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0,NaN
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9998,15584532,Liu,709,France,Female,36,7,0K,1,0,1,42085.58,1,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN
10000,15628319,Walker,792,France,Female,28,4,130K,1,1,0,38190.78,0,NaN

In [116]:
type(churn)

pandas.core.frame.DataFrame

In [117]:
#set the RowNumber (Column zero) as the DataFrame Index
#this replaces the default index created by pandas
#notice we have one less column (14 instead of 15)
churn = pd.read_csv(project_dir+ 'Churn-Modelling.csv', index_col=0)
churn

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1,NaN
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0,NaN
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1,NaN
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0,NaN
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9998,15584532,Liu,709,France,Female,36,7,0K,1,0,1,42085.58,1,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN
10000,15628319,Walker,792,France,Female,28,4,130K,1,1,0,38190.78,0,NaN

# Simple Exporatory Data Analysis (EDA)

In [118]:
churn.head(7)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1,NaN
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0,NaN
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1,NaN
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0,NaN
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0,NaN
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1,NaN
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN

In [119]:
churn.tail(10)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
9991,15798964,Nkemakonam,714,Germany,Male,33,3,35K,1,1,0,53667.08,0,NaN
9992,15769959,Ajuluchukwu,597,France,Female,53,4,88K,1,1,0,69384.71,1,NaN
9993,15657105,Chukwualuka,726,Spain,Male,36,2,0K,1,1,0,195192.40,0,NaN
9994,15569266,Rahman,644,France,Male,28,7,155K,1,1,0,29179.52,0,NaN
9995,15719294,Wood,800,France,Female,29,2,0K,2,0,0,167773.55,0,NaN
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9998,15584532,Liu,709,France,Female,36,7,0K,1,0,1,42085.58,1,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN
10000,15628319,Walker,792,France,Female,28,4,130K,1,1,0,38190.78,0,NaN

In [120]:
churn.sample(5)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
3863,15726588,Seleznev,653,Spain,Female,36,3,0K,2,0,0,110525.60,0,NaN
8644,15813660,Forlonge,754,Spain,Male,40,2,161K,1,0,1,3554.63,0,NaN
1847,15812338,Sopuluchukwu,485,Spain,Female,30,7,0K,1,1,0,107067.37,0,NaN
5043,15593468,Findlay,850,France,Female,33,3,0K,2,1,1,11159.19,0,NaN
5167,15694644,Wood,455,Spain,Female,43,6,0K,1,1,1,81250.79,0,NaN

In [121]:
churn.sample(5, random_state=9)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
3645,15626233,Onyekachi,593,France,Female,32,3,0K,2,1,1,151978.36,0,NaN
9185,15716984,Palermo,695,Spain,Female,56,4,0K,2,1,0,84644.76,0,NaN
521,15671256,Macartney,850,France,Female,35,1,212K,1,1,0,188574.12,1,NaN
5686,15811565,Cocci,705,Spain,Female,47,3,63K,1,0,1,28640.92,1,NaN
2402,15751336,Yao,630,Spain,Male,30,3,0K,2,0,1,10486.69,0,NaN

In [122]:
type(churn)

pandas.core.frame.DataFrame

In [123]:
churn.shape

(10000, 14)

In [124]:
churn.shape[1]

14

In [125]:
churn.shape[0]

10000

In [126]:
type(churn.shape)

tuple

In [127]:
# Try this
# churn.shape[2]

In [128]:
churn.shape[-1]

14

In [129]:
churn.shape[-2]

10000

In [130]:
# churn.shape[-3]

In [131]:
type (churn.shape[1])

int

#  Row/Column Selection

In [132]:
churn.Gender == 'Male'

RowNumber
1        False
2        False
3        False
4        False
5        False
         ...
9996      True
9997      True
9998     False
9999      True
10000    False
Name: Gender, Length: 10000, dtype: bool

In [133]:
type(churn.Gender == 'Male')

pandas.core.series.Series

In [134]:
males =  churn[churn.Gender == 'Male']
males

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1,NaN
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN
9,15792365,He,501,France,Male,44,4,142K,2,0,1,74940.50,0,NaN
10,15592389,H?,684,France,Male,27,2,135K,1,1,1,71725.73,0,NaN
11,15767821,Bearce,528,France,Male,31,6,102K,2,0,0,80181.12,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,15657105,Chukwualuka,726,Spain,Male,36,2,0K,1,1,0,195192.40,0,NaN
9994,15569266,Rahman,644,France,Male,28,7,155K,1,1,0,29179.52,0,NaN
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN

In [135]:
male_French_Filter = (churn.Gender == 'Male') & (churn.Geography == 'France')
churn[male_French_Filter]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN
9,15792365,He,501,France,Male,44,4,142K,2,0,1,74940.50,0,NaN
10,15592389,H?,684,France,Male,27,2,135K,1,1,1,71725.73,0,NaN
11,15767821,Bearce,528,France,Male,31,6,102K,2,0,0,80181.12,0,NaN
21,15577657,McDonald,732,France,Male,41,8,0K,2,1,1,170886.17,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,15586914,Nepean,659,France,Male,36,6,124K,2,1,0,96833.00,0,NaN
9989,15589329,Pirozzi,775,France,Male,30,4,0K,2,1,0,49337.84,0,NaN
9994,15569266,Rahman,644,France,Male,28,7,155K,1,1,0,29179.52,0,NaN
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN

In [136]:
type(males)

pandas.core.frame.DataFrame

In [137]:
males.shape

(5457, 14)

In [138]:
males.shape[0]

5457

In [139]:
males.shape[0]/churn.shape[0]

0.5457

In [140]:
churn['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [141]:
churn['Gender'].value_counts()[0]

5457

In [142]:
churn['Gender'].value_counts()[1]

4543

In [143]:
type(churn['Gender'].value_counts())

pandas.core.series.Series

In [144]:
churn['Gender'].value_counts()/churn.shape[0]

Male      0.5457
Female    0.4543
Name: Gender, dtype: float64

In [145]:
churn['Gender'].value_counts(normalize=True)

Male      0.5457
Female    0.4543
Name: Gender, dtype: float64

In [146]:
churn['Gender'].value_counts()[0]/churn.shape[0]

0.5457



---


 ***Select Column from a DataFrame***

In [147]:
# Select column from DataFrame
males.Surname

RowNumber
6               Chu
7          Bartlett
9                He
10               H?
11           Bearce
           ...
9993    Chukwualuka
9994         Rahman
9996       Obijiaku
9997      Johnstone
9999      Sabbatini
Name: Surname, Length: 5457, dtype: object

In [148]:
# Select column from DataFrame
males['Surname']

RowNumber
6               Chu
7          Bartlett
9                He
10               H?
11           Bearce
           ...
9993    Chukwualuka
9994         Rahman
9996       Obijiaku
9997      Johnstone
9999      Sabbatini
Name: Surname, Length: 5457, dtype: object

In [149]:
# Select column from DataFrame
males.loc[:,'Surname']

RowNumber
6               Chu
7          Bartlett
9                He
10               H?
11           Bearce
           ...
9993    Chukwualuka
9994         Rahman
9996       Obijiaku
9997      Johnstone
9999      Sabbatini
Name: Surname, Length: 5457, dtype: object

In [150]:
males.iloc[:,1]

RowNumber
6               Chu
7          Bartlett
9                He
10               H?
11           Bearce
           ...
9993    Chukwualuka
9994         Rahman
9996       Obijiaku
9997      Johnstone
9999      Sabbatini
Name: Surname, Length: 5457, dtype: object

In [151]:
type(males['Surname'])

pandas.core.series.Series



---


***Select row***

In [152]:
males.head(10)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1,NaN
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN
9,15792365,He,501,France,Male,44,4,142K,2,0,1,74940.50,0,NaN
10,15592389,H?,684,France,Male,27,2,135K,1,1,1,71725.73,0,NaN
11,15767821,Bearce,528,France,Male,31,6,102K,2,0,0,80181.12,0,NaN
12,15737173,Andrews,497,Spain,Male,24,3,0K,2,1,0,76390.01,0,NaN
16,15643966,Goforth,616,Germany,Male,45,3,143K,2,0,1,64327.26,0,NaN
17,15737452,Romeo,653,Germany,Male,58,1,133K,1,1,0,5097.67,1,NaN
19,15661507,Muldrow,587,Spain,Male,45,6,0K,1,0,0,158684.81,0,NaN
21,15577657,McDonald,732,France,Male,41,8,0K,2,1,1,170886.17,0,NaN

In [153]:
males.iloc[6, :]

CustomerId         15643966
Surname             Goforth
CreditScore             616
Geography           Germany
Gender                 Male
Age                      45
Tenure                    3
Balance                143K
NumOfProducts             2
HasCrCard                 0
IsActiveMember            1
EstimatedSalary    64327.26
Exited                    0
Unnamed: 14             NaN
Name: 16, dtype: object

In [154]:
males.loc[6, :]

CustomerId          15574012
Surname                  Chu
CreditScore              645
Geography              Spain
Gender                  Male
Age                       44
Tenure                     8
Balance                 114K
NumOfProducts              2
HasCrCard                  1
IsActiveMember             0
EstimatedSalary    149756.71
Exited                     1
Unnamed: 14              NaN
Name: 6, dtype: object

In [155]:
males.loc[6, 'Surname']

'Chu'

In [156]:
males.loc[:, :]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1,NaN
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN
9,15792365,He,501,France,Male,44,4,142K,2,0,1,74940.50,0,NaN
10,15592389,H?,684,France,Male,27,2,135K,1,1,1,71725.73,0,NaN
11,15767821,Bearce,528,France,Male,31,6,102K,2,0,0,80181.12,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,15657105,Chukwualuka,726,Spain,Male,36,2,0K,1,1,0,195192.40,0,NaN
9994,15569266,Rahman,644,France,Male,28,7,155K,1,1,0,29179.52,0,NaN
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN

In [157]:
males.iloc[:, :]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1,NaN
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN
9,15792365,He,501,France,Male,44,4,142K,2,0,1,74940.50,0,NaN
10,15592389,H?,684,France,Male,27,2,135K,1,1,1,71725.73,0,NaN
11,15767821,Bearce,528,France,Male,31,6,102K,2,0,0,80181.12,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,15657105,Chukwualuka,726,Spain,Male,36,2,0K,1,1,0,195192.40,0,NaN
9994,15569266,Rahman,644,France,Male,28,7,155K,1,1,0,29179.52,0,NaN
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN

In [158]:
males.loc[:, :].sample(2)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
8873,15626475,Gamble,685,France,Male,30,2,0K,2,1,1,140889.32,0,NaN
5393,15710012,Bowen,738,Spain,Male,44,2,0K,2,1,0,43018.82,1,NaN

In [159]:
type(males.iloc[6, :])

pandas.core.series.Series

Notice that individual Pandas DataFrame columns and rows are type "Series"

In [160]:
churn[churn.Gender== 'Male']

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14
RowNumber,,,,,,,,,,,,,,
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1,NaN
7,15592531,Bartlett,822,France,Male,50,7,0K,2,1,1,10062.80,0,NaN
9,15792365,He,501,France,Male,44,4,142K,2,0,1,74940.50,0,NaN
10,15592389,H?,684,France,Male,27,2,135K,1,1,1,71725.73,0,NaN
11,15767821,Bearce,528,France,Male,31,6,102K,2,0,0,80181.12,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,15657105,Chukwualuka,726,Spain,Male,36,2,0K,1,1,0,195192.40,0,NaN
9994,15569266,Rahman,644,France,Male,28,7,155K,1,1,0,29179.52,0,NaN
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0,NaN
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0,NaN
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1,NaN

In [161]:
churn.groupby(["Geography", "Gender"])["Exited"].count()

Geography  Gender
France     Female    2261
           Male      2753
Germany    Female    1193
           Male      1316
Spain      Female    1089
           Male      1388
Name: Exited, dtype: int64

In [162]:
# data_groupby_sex_describe=data.groupby('SEX').describe()

In [163]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 1 to 10000
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  object
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
 13  Unnamed: 14      0 non-null      float64
dtypes: float64(2), int64(8), object(4)
memory usage: 1.1+ MB

In [164]:
churn['Age'].isna()

RowNumber
1        False
2        False
3        False
4        False
5        False
         ...
9996     False
9997     False
9998     False
9999     False
10000    False
Name: Age, Length: 10000, dtype: bool

In [165]:
# churn.count().isnull()
churn['Age'].isna().sum()

0

### Remove column with all nulls

In [166]:
churn['Unnamed: 14'].isna().sum()

10000

In [167]:
# all the content of column 13 is NaN (NaN), we can safely delete this column
churn['Unnamed: 14']

RowNumber
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
         ..
9996    NaN
9997    NaN
9998    NaN
9999    NaN
10000   NaN
Name: Unnamed: 14, Length: 10000, dtype: float64

In [168]:
churn[:5].isna().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
Unnamed: 14        5
dtype: int64

In [169]:
del churn['Unnamed: 14']

In [170]:
# we now have 13 columns
churn

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,Obijiaku,771,France,Male,39,5,0K,2,1,0,96270.64,0
9997,15569892,Johnstone,516,France,Male,35,10,57K,1,1,1,101699.77,0
9998,15584532,Liu,709,France,Female,36,7,0K,1,0,1,42085.58,1
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1
10000,15628319,Walker,792,France,Female,28,4,130K,1,1,0,38190.78,0

In [171]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 1 to 10000
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  object
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(1), int64(8), object(4)
memory usage: 1.1+ MB

# selcting rows

In [172]:
# selecting by rows
churn[1:5]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0

In [173]:
churn[0:5]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0

In [174]:
churn[-2:-1]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
9999,15682355,Sabbatini,772,Germany,Male,42,3,75K,2,1,0,92888.52,1

In [175]:
churn.head(6)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0K,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,84K,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,160K,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0K,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,126K,1,1,1,79084.10,0
6,15574012,Chu,645,Spain,Male,44,8,114K,2,1,0,149756.71,1

In [176]:
churn.loc[5,'CustomerId']

15737888

In [177]:
churn.iloc[4,0]

15737888

In [178]:
males.loc[6,'CustomerId']

15574012

In [179]:
# churn.loc[0,'CustomerId']

In [180]:
churn.iloc[4,0]

15737888

In [181]:
churn.loc[:,'CustomerId']

RowNumber
1        15634602
2        15647311
3        15619304
4        15701354
5        15737888
           ...
9996     15606229
9997     15569892
9998     15584532
9999     15682355
10000    15628319
Name: CustomerId, Length: 10000, dtype: int64

In [182]:
churn.iloc[:,5]

RowNumber
1        42
2        41
3        42
4        39
5        43
         ..
9996     39
9997     35
9998     36
9999     42
10000    28
Name: Age, Length: 10000, dtype: int64

In [183]:
churn[:5].isna().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [184]:
churn.describe()

,CustomerId,CreditScore,Age,Tenure,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,4.000000,1.00000,1.000000,199992.480000,1.000000

### Validate Existed Percentage

In [185]:
churn['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [186]:
churn['Exited'].value_counts()[1]/churn.shape[0]

0.2037

In [187]:
exited_percentage = ((churn.Exited == 1).value_counts(normalize=True))
exited_percentage

False    0.7963
True     0.2037
Name: Exited, dtype: float64

In [188]:
exited_percentage[1]

0.2037

In [189]:
# overall correlations
churn.corr()

<ipython-input-189-30d3eb871eed>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  churn.corr()

,CustomerId,CreditScore,Age,Tenure,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,1.000000,0.005308,0.009497,-0.014883,0.016972,-0.014025,0.001665,0.015271,-0.006248
CreditScore,0.005308,1.000000,-0.003965,0.000842,0.012238,-0.005458,0.025651,-0.001384,-0.027094
Age,0.009497,-0.003965,1.000000,-0.009997,-0.030680,-0.011721,0.085472,-0.007201,0.285323
Tenure,-0.014883,0.000842,-0.009997,1.000000,0.013444,0.022583,-0.028362,0.007784,-0.014001
NumOfProducts,0.016972,0.012238,-0.030680,0.013444,1.000000,0.003183,0.009612,0.014204,-0.047820
HasCrCard,-0.014025,-0.005458,-0.011721,0.022583,0.003183,1.000000,-0.011866,-0.009933,-0.007138
IsActiveMember,0.001665,0.025651,0.085472,-0.028362,0.009612,-0.011866,1.000000,-0.011421,-0.156128
EstimatedSalary,0.015271,-0.001384,-0.007201,0.007784,0.014204,-0.009933,-0.011421,1.000000,0.012097
Exited,-0.006248,-0.027094,0.285323,-0.014001,-0.047820,-0.007138,-0.156128,0.012097,1.000000

In [190]:
churn.describe(include=['O'])

       Surname Geography Gender Balance
count    10000     10000  10000   10000
unique    2932         3      2     195
top      Smith    France   Male      0K
freq        32      5014   5457    3617

In [191]:
churn.describe(include='all')

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,2932,NaN,3,2,NaN,NaN,195,NaN,NaN,NaN,NaN,NaN
top,NaN,Smith,NaN,France,Male,NaN,NaN,0K,NaN,NaN,NaN,NaN,NaN
freq,NaN,32,NaN,5014,5457,NaN,NaN,3617,NaN,NaN,NaN,NaN,NaN
mean,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,NaN,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,NaN,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,NaN,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,NaN,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,NaN,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,NaN,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,NaN,4.000000,1.00000,1.000000,199992.480000,1.000000

### Cleanup Balance Column

In [192]:
churn['Balance'] =  churn["Balance"].str.replace('K','').astype('int')
churn

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,84,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,160,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,126,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,Obijiaku,771,France,Male,39,5,0,2,1,0,96270.64,0
9997,15569892,Johnstone,516,France,Male,35,10,57,1,1,1,101699.77,0
9998,15584532,Liu,709,France,Female,36,7,0,1,0,1,42085.58,1
9999,15682355,Sabbatini,772,Germany,Male,42,3,75,2,1,0,92888.52,1
10000,15628319,Walker,792,France,Female,28,4,130,1,1,0,38190.78,0

In [193]:
# churn.loc[:,'Balance'] = churn['Balance'].str.replace("K", '').astype(int)
# churn.sample(2)

In [194]:
# churn['Balance'] = churn['Balance'].str.replace('K',' ')
# churn['Balance'] = churn['Balance'].astype('int64')

In [195]:
churn

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,84,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,160,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,126,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,Obijiaku,771,France,Male,39,5,0,2,1,0,96270.64,0
9997,15569892,Johnstone,516,France,Male,35,10,57,1,1,1,101699.77,0
9998,15584532,Liu,709,France,Female,36,7,0,1,0,1,42085.58,1
9999,15682355,Sabbatini,772,Germany,Male,42,3,75,2,1,0,92888.52,1
10000,15628319,Walker,792,France,Female,28,4,130,1,1,0,38190.78,0

In [196]:
churn.describe(include='all')

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
unique,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76.489000,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62.401569,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97.000000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,128.000000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,251.000000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [197]:
g1 = churn.groupby(['Gender']).size(); g1

Gender
Female    4543
Male      5457
dtype: int64

In [198]:
churn['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [199]:
churn['Gender'].value_counts(normalize=True)

Male      0.5457
Female    0.4543
Name: Gender, dtype: float64

In [200]:
g1 = churn.groupby(['Geography']).size(); g1

Geography
France     5014
Germany    2509
Spain      2477
dtype: int64

In [201]:
churn['Geography'].value_counts(normalize=True)

France     0.5014
Germany    0.2509
Spain      0.2477
Name: Geography, dtype: float64

# Additional EDA

In [202]:
churn['Age']

RowNumber
1        42
2        41
3        42
4        39
5        43
         ..
9996     39
9997     35
9998     36
9999     42
10000    28
Name: Age, Length: 10000, dtype: int64

In [203]:
churn.Age

RowNumber
1        42
2        41
3        42
4        39
5        43
         ..
9996     39
9997     35
9998     36
9999     42
10000    28
Name: Age, Length: 10000, dtype: int64

In [204]:
type(churn.Age)

pandas.core.series.Series

In [205]:
churn[['Age']]

           Age
RowNumber
1           42
2           41
3           42
4           39
5           43
...        ...
9996        39
9997        35
9998        36
9999        42
10000       28

[10000 rows x 1 columns]

In [206]:
type(churn['Age'])

pandas.core.series.Series

In [207]:
type(churn[['Age']])

pandas.core.frame.DataFrame

In [208]:
Age = churn['Age']
Age

RowNumber
1        42
2        41
3        42
4        39
5        43
         ..
9996     39
9997     35
9998     36
9999     42
10000    28
Name: Age, Length: 10000, dtype: int64

In [209]:
Age = churn.Age
Age

RowNumber
1        42
2        41
3        42
4        39
5        43
         ..
9996     39
9997     35
9998     36
9999     42
10000    28
Name: Age, Length: 10000, dtype: int64

In [210]:
type(Age)

pandas.core.series.Series

In [211]:
churn['Age'].value_counts()

37    478
38    477
35    474
36    456
34    447
     ...
92      2
82      1
88      1
85      1
83      1
Name: Age, Length: 70, dtype: int64

In [212]:
churn['Age'].describe()

count    10000.000000
mean        38.921800
std         10.487806
min         18.000000
25%         32.000000
50%         37.000000
75%         44.000000
max         92.000000
Name: Age, dtype: float64

In [213]:
churn['Age'].describe()[1]

38.9218

In [214]:
churn['Age'].describe()[-1]

92.0

In [215]:
churn['Age'].mean()

38.9218

In [216]:
churn['Exited'].value_counts(normalize=True)

0    0.7963
1    0.2037
Name: Exited, dtype: float64

# Change column order

In [217]:
churn.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [218]:
col_names = churn.columns[::-1]
col_names

Index(['Exited', 'EstimatedSalary', 'IsActiveMember', 'HasCrCard',
       'NumOfProducts', 'Balance', 'Tenure', 'Age', 'Gender', 'Geography',
       'CreditScore', 'Surname', 'CustomerId'],
      dtype='object')

In [219]:
newColOrder = ['CustomerId', 'Geography','Surname', 'CreditScore', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited']
churn = churn[newColOrder]
churn

,CustomerId,Geography,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,France,Hargrave,619,Female,42,2,0,1,1,1,101348.88,1
2,15647311,Spain,Hill,608,Female,41,1,84,1,0,1,112542.58,0
3,15619304,France,Onio,502,Female,42,8,160,3,1,0,113931.57,1
4,15701354,France,Boni,699,Female,39,1,0,2,0,0,93826.63,0
5,15737888,Spain,Mitchell,850,Female,43,2,126,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,France,Obijiaku,771,Male,39,5,0,2,1,0,96270.64,0
9997,15569892,France,Johnstone,516,Male,35,10,57,1,1,1,101699.77,0
9998,15584532,France,Liu,709,Female,36,7,0,1,0,1,42085.58,1
9999,15682355,Germany,Sabbatini,772,Male,42,3,75,2,1,0,92888.52,1
10000,15628319,France,Walker,792,Female,28,4,130,1,1,0,38190.78,0

# change the index

In [220]:
print (churn.CustomerId.count())
print (churn.CustomerId.nunique())

10000
10000

In [221]:
# churn = churn.set_index('CustomerId')
# churn

In [222]:
churn.set_index('CustomerId', inplace=True)
churn

,Geography,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,
15634602,France,Hargrave,619,Female,42,2,0,1,1,1,101348.88,1
15647311,Spain,Hill,608,Female,41,1,84,1,0,1,112542.58,0
15619304,France,Onio,502,Female,42,8,160,3,1,0,113931.57,1
15701354,France,Boni,699,Female,39,1,0,2,0,0,93826.63,0
15737888,Spain,Mitchell,850,Female,43,2,126,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
15606229,France,Obijiaku,771,Male,39,5,0,2,1,0,96270.64,0
15569892,France,Johnstone,516,Male,35,10,57,1,1,1,101699.77,0
15584532,France,Liu,709,Female,36,7,0,1,0,1,42085.58,1
15682355,Germany,Sabbatini,772,Male,42,3,75,2,1,0,92888.52,1
15628319,France,Walker,792,Female,28,4,130,1,1,0,38190.78,0

In [223]:
churn.shape

(10000, 12)

### Cleanup Balance Column

In [224]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 15634602 to 15628319
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Geography        10000 non-null  object
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Gender           10000 non-null  object
 4   Age              10000 non-null  int64
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  int64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64
dtypes: float64(1), int64(8), object(3)
memory usage: 1015.6+ KB

In [225]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 15634602 to 15628319
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Geography        10000 non-null  object
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Gender           10000 non-null  object
 4   Age              10000 non-null  int64
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  int64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64
dtypes: float64(1), int64(8), object(3)
memory usage: 1015.6+ KB

### Change column data type (Type Casting)

In [226]:
churn['Geography'] = churn['Geography'].astype('category')
churn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 15634602 to 15628319
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Geography        10000 non-null  category
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Gender           10000 non-null  object
 4   Age              10000 non-null  int64
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  int64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64
dtypes: category(1), float64(1), int64(8), object(2)
memory usage: 947.4+ KB