In [85]:
import pandas as pd
import random
from datetime import datetime, timedelta

# Function to generate random dates within a specific range
def random_date(start_date, end_date):
    delta = end_date - start_date
    random_days = random.randint(0, delta.days)
    return start_date + timedelta(days=random_days)

# Generating 2000 entries of mock data with additional logic
start_date = datetime(2020, 1, 1)
end_date = datetime(2022, 12, 31)

In [86]:
data = {
    'Date': [],
    'Product': [],
    'Product Type': [],
    'Region': [],
    'Distance from Collection Point': [],
    'Sales in units': [],
    'Returned Quantity in units': [],
    'Bootle Returned Damaged': [],
    'Manufacturing cost of bottle': [],
    'Profit from bottle reusage': [],
    'Loss of returned Bottle': [],
    'Loss from Damaged Bottle': [],
    'Reused Returned Bottles': []
}

regions = ['North', 'South', 'East', 'West']
products = ['A', 'B', 'C']
product_types = ['Type1', 'Type2']
manufacturing_costs = [2.0, 2.5, 3.0]
profits = [1.0, 1.5, 2.0]
losses = [0.3, 0.5, 0.7]

salein_units = [60000, 102000]

In [87]:
for _ in range(2000):
    distance = random.randint(10, 250)
    returned_quantity = round(random.randint(min(salein_units), max(salein_units))* random.uniform(0.75, 0.95))
    distance_factor = random.uniform(0.05, 0.15)
    
    # Applying logic based on distance
    decreased_quantity = int(returned_quantity - (returned_quantity * distance_factor))
    damaged_bottles = int(distance * distance_factor + returned_quantity*distance_factor)
    reused_bottles = returned_quantity - damaged_bottles
    
    data['Date'].append(random_date(start_date, end_date))
    data['Product'].append(random.choice(products))
    data['Product Type'].append(random.choice(product_types))
    data['Region'].append(random.choice(regions))
    data['Distance from Collection Point'].append(distance)
    data['Sales in units'].append(random.randint(60000, 102000))
    data['Returned Quantity in units'].append(returned_quantity)
    data['Bootle Returned Damaged'].append(damaged_bottles)
    data['Manufacturing cost of bottle'].append(random.choice(manufacturing_costs))
    data['Profit from bottle reusage'].append(random.choice(profits))
    data['Loss of returned Bottle'].append(random.choice(losses))
    data['Loss from Damaged Bottle'].append(random.choice(losses))
    data['Reused Returned Bottles'].append(reused_bottles)

    data['year'] = pd.DatetimeIndex(data['Date']).year
    data['month'] = pd.DatetimeIndex(data['Date']).month
    data['Month Name'] = pd.DatetimeIndex(data['Date']).month_name()
    data['Quarter'] = [f'Q{m//3 + 1}' for m in data['month']]

In [88]:
df['Profit from bottle reusage'] = df['Manufacturing cost of bottle']* df['Reused Returned Bottles']
df['Loss of returned Bottle'] = (df['Manufacturing cost of bottle']* df['Sales in units']) - (df['Manufacturing cost of bottle'] * df['Returned Quantity in units'])
df['Loss from Damaged Bottle'] = df['Manufacturing cost of bottle']* df['Bootle Returned Damaged']


df.head()

#

,Date,Product,Product Type,Region,Distance from Collection Point,Sales in units,Returned Quantity in units,Bootle Returned Damaged,Manufacturing cost of bottle,Profit from bottle reusage,Loss of returned Bottle,Loss from Damaged Bottle,Reused Returned Bottles,year,month,Month Name,day,Quarter
0,2021-07-15,7up,500ml,East,103,79618,68300,4953,2.5,158367.5,28295.0,12382.5,63347,2021,7,July,15,Q3
1,2021-10-09,PEPSI,250ml,East,175,73390,82598,10177,2.5,181052.5,-23020.0,25442.5,72421,2021,10,October,9,Q4
2,2020-04-11,PEPSI,500ml,East,108,89228,68580,7414,2.5,152915.0,51620.0,18535.0,61166,2020,4,April,11,Q2
3,2020-03-21,7up,500ml,East,208,78116,47846,5227,3.0,127857.0,90810.0,15681.0,42619,2020,3,March,21,Q2
4,2022-02-02,PEPSI,500ml,West,51,94047,53176,7331,2.0,91690.0,81742.0,14662.0,45845,2022,2,February,2,Q1

In [89]:
# if product is of Type1 then replace it with 500ml and if it is of Type2 then replace it with 250ml
df['Product Type'] = df['Product Type'].replace({'Type1': '500ml', 'Type2': '250ml'})
df['Product'] = df['Product'].replace({'A': 'PEPSI', 'B': 'Mountain Dew', 'C': '7up'})
df.drop(columns=['month', 'day'])
df.head()

,Date,Product,Product Type,Region,Distance from Collection Point,Sales in units,Returned Quantity in units,Bootle Returned Damaged,Manufacturing cost of bottle,Profit from bottle reusage,Loss of returned Bottle,Loss from Damaged Bottle,Reused Returned Bottles,year,month,Month Name,day,Quarter
0,2021-07-15,7up,500ml,East,103,79618,68300,4953,2.5,158367.5,28295.0,12382.5,63347,2021,7,July,15,Q3
1,2021-10-09,PEPSI,250ml,East,175,73390,82598,10177,2.5,181052.5,-23020.0,25442.5,72421,2021,10,October,9,Q4
2,2020-04-11,PEPSI,500ml,East,108,89228,68580,7414,2.5,152915.0,51620.0,18535.0,61166,2020,4,April,11,Q2
3,2020-03-21,7up,500ml,East,208,78116,47846,5227,3.0,127857.0,90810.0,15681.0,42619,2020,3,March,21,Q2
4,2022-02-02,PEPSI,500ml,West,51,94047,53176,7331,2.0,91690.0,81742.0,14662.0,45845,2022,2,February,2,Q1

In [90]:
df.to_csv('bottledata_Final.csv', index=False)